enabled: true
name: app1
replicaCount: 2

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  config:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10

readinessProbe:
  enabled: true
  config:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5

startupProbe:
  enabled: true
  config:
    httpGet:
      path: /
      port: http
    failureThreshold: 30
    periodSeconds: 10

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: app1.local
      paths:
        - path: /
          pathType: Prefix